In [1]:
import requests
import pandas as pd
import os
from pathlib import Path

# Paths based on structure
PROJECT_DIR = Path("..")
REF_DIR = PROJECT_DIR / "data" / "reference"
YEARLY_DIR = PROJECT_DIR / "outputs" / "yearly"

REF_DIR.mkdir(parents=True, exist_ok=True)

print("Reference directory:", REF_DIR.resolve())
print("Yearly parquet directory:", YEARLY_DIR.resolve())

Reference directory: /Users/francobastida/Desktop/ecobici/data/reference
Yearly parquet directory: /Users/francobastida/Desktop/ecobici/outputs/yearly

In [2]:
# GBFS API pull, since there is no historical data
GBFS_ROOT_URL = "https://gbfs.mex.lyftbikes.com/gbfs/gbfs.json"

response = requests.get(GBFS_ROOT_URL, timeout=30)
response.raise_for_status()

gbfs_root = response.json()

In [3]:
gbfs_root

{'last_updated': 1774139317,
 'ttl': 10,
 'data': {'en': {'feeds': [{'name': 'station_status',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/en/station_status.json'},
    {'name': 'system_information',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/en/system_information.json'},
    {'name': 'station_information',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/en/station_information.json'},
    {'name': 'system_alerts',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/en/system_alerts.json'},
    {'name': 'free_bike_status',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/en/free_bike_status.json'}]},
  'es': {'feeds': [{'name': 'station_status',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/es/station_status.json'},
    {'name': 'system_information',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/es/system_information.json'},
    {'name': 'station_information',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/es/station_information.json'},
    {'name': 'system_alerts',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/es/system_alerts.json'},
    {'name': 'free_bike_status',
     'url': 'https://gbfs.mex.lyftbikes.com/gbfs/es/free_bike_status.json'}]}}}

In [4]:
# Extract station_information URL
feeds = gbfs_root["data"]["en"]["feeds"]
feeds_df = pd.DataFrame(feeds)

station_info_url = feeds_df.loc[
    feeds_df["name"] == "station_information", "url"
].iloc[0]

# Download station info
station_response = requests.get(station_info_url, timeout=30)
station_response.raise_for_status()

station_json = station_response.json()

In [5]:
station_json

{'last_updated': 1774139317,
 'ttl': 10,
 'data': {'stations': [{'station_id': '1',
    'external_id': 'e961269c-34c4-4b70-8e30-a51aa95a8429',
    'name': 'CE-710 Molino del Rey - Glorieta de la Lealtad',
    'short_name': '710',
    'lat': 19.416795,
    'lon': -99.192508,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 39,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '5',
    'external_id': '3ea89109-d2f3-46eb-9c41-c43742050340',
    'name': 'CE-407  Prolongación Xochicalco-General Emiliano Zapata',
    'short_name': '407',
    'lat': 19.36726591257277,
    'lon': -99.15865559132271,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '6',
    'external_id': 'ba78b703-4e5a-44bd-ab2c-1eedc71e11c3',
    'name': 'CE-428  Prolongación Uxmal-Av. Popocatépetl (Eje 8)',
    'short_name': '428',
    'lat': 19.363404,
    'lon': -99.160395,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '7',
    'external_id': '6563d263-2342-46e3-8983-461e68d2d615',
    'name': 'CE-427 Avenida México-Coyoacán-Av. Popocatépetl (Eje 8)',
    'short_name': '427',
    'lat': 19.364905637923787,
    'lon': -99.1629866883295,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '8',
    'external_id': 'ec55e597-c8fc-4e86-bcfe-b0e81a494790',
    'name': 'CE-443 Bruno Traven-Golondrinas',
    'short_name': '443',
    'lat': 19.359583,
    'lon': -99.162085,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '9',
    'external_id': 'a98c7fac-12ce-4895-923b-6b39f04721ca',
    'name': 'CE-423 Moras-José María Rico (Eje 8)',
    'short_name': '423',
    'lat': 19.367816,
    'lon': -99.175269,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '10',
    'external_id': 'ae1c2b82-7148-41c2-acd1-d9280241f87e',
    'name': 'CE-438 Adolfo Prieto-José María Olloqui',
    'short_name': '438',
    'lat': 19.36473,
    'lon': -99.174447,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '11',
    'external_id': 'f6484d2e-8282-41e6-a023-1afb53dae580',
    'name': 'CE-415 San Francisco-Parroquia',
    'short_name': '415',
    'lat': 19.37099,
    'lon': -99.176135,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '12',
    'external_id': '90714c5e-7256-4744-a55d-9370f26d89bd',
    'name': 'CE-417 Goya-Augusto Rodin',
    'short_name': '417',
    'lat': 19.373447,
    'lon': -99.184465,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '14',
    'external_id': '1995f5cd-611e-4571-832d-57f4d19ffc57',
    'name': 'CE-022 Reforma - Manchester',
    'short_name': '022',
    'lat': 19.424784,
    'lon': -99.172119,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 35,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '15',
    'external_id': '2f3047ad-7725-4d23-9e59-3b98aeee9f3d',
    'name': 'CE-094 Lic. Verdad-Moneda',
    'short_name': '094',
    'lat': 19.433766,
    'lon': -99.130918,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '16',
    'external_id': 'd821ac72-6eb9-47ba-8e9d-b288db2d99d1',
    'name': 'CE-405 División Del Norte-Municipio Libre',
    'short_name': '405',
    'lat': 19.370565558464016,
    'lon': -99.15662247688942,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '17',
    'external_id': '4f21a08a-24f2-465e-b8f3-5874d064e015',
    'name': 'CE-375 Tenayuca-División Del Norte',
    'short_name': '375',
    'lat': 19.376793,
    'lon': -99.158847,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '18',
    'external_id': 'ac88b65c-7622-4b42-84bd-b9c3f36f7d22',
    'name': 'CE-394 Dr. Roberto Gayol-Félix Cuevas',
    'short_name': '394',
    'lat': 19.372474,
    'lon': -99.171639,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 35,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '19',
    'external_id': '08164fbf-ce81-4db0-9bf3-98845325dfa6',
    'name': 'CE-337 San Borja-Martín Mendalde',
    'short_name': '337',
    'lat': 19.384849,
    'lon': -99.16704,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '20',
    'external_id': '8c4eceec-211c-4064-b923-97c71f09b1a7',
    'name': 'CE-412 Parroquia-Avenida Universidad',
    'short_name': '412',
    'lat': 19.368107,
    'lon': -99.164376,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 34,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '21',
    'external_id': '616c0715-1a8e-492b-85cb-452f062ca42b',
    'name': 'CE-381 San Lorenzo-Manzanas',
    'short_name': '381',
    'lat': 19.375543381100602,
    'lon': -99.17801052342838,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '22',
    'external_id': 'f9827216-5cfa-4eb1-a912-096b9545fa83',
    'name': 'CE-332 Calle 27-Avenida 3',
    'short_name': '332',
    'lat': 19.385494,
    'lon': -99.183744,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '23',
    'external_id': 'ef08f966-4d87-4fdc-b783-287605e9c117',
    'name': 'CE-399 Heriberto Frías-San Lorenzo',
    'short_name': '399',
    'lat': 19.372469,
    'lon': -99.164538,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 35,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '24',
    'external_id': '78a8e829-3e75-40fd-9543-3ca0cbc15747',
    'name': 'CE-377 Heriberto Frías-Miguel Laurent',
    'short_name': '377',
    'lat': 19.375397,
    'lon': -99.163778,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 35,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '25',
    'external_id': '287e590f-e27b-4211-8fb5-9b11bd2fd0cd',
    'name': 'CE-360 Heriberto Frías-Matias Romero',
    'short_name': '360',
    'lat': 19.379435,
    'lon': -99.162794,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '26',
    'external_id': 'd353123d-74b4-405b-8257-a61eb1d771ee',
    'name': 'CE-362 Augusto Rodin-Alberto Balderas',
    'short_name': '362',
    'lat': 19.382123281154726,
    'lon': -99.18109126394484,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '27',
    'external_id': 'df57391d-94b4-497a-86f0-0681ef80704a',
    'name': 'CE-365 Holbein-Avenida Revolución',
    'short_name': '365',
    'lat': 19.381123,
    'lon': -99.18667,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 21,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '28',
    'external_id': '4129eb20-73b3-4e3b-b473-a939ab14156f',
    'name': 'CE-424 Amores-José María Rico (Eje 8)',
    'short_name': '424',
    'lat': 19.367103332434564,
    'lon': -99.17058136315518,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 11,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '29',
    'external_id': '22226b72-86e9-4fb9-9f0c-38447c7daa97',
    'name': 'CE-421 María Luz Bringas-Oso',
    'short_name': '421',
    'lat': 19.36952,
    'lon': -99.179421,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '30',
    'external_id': '518b8a91-e2d4-4892-9bb5-caf4f558032f',
    'name': 'CE-287 13 de Septiembre-Puente de la Morena',
    'short_name': '287',
    'lat': 19.398946,
    'lon': -99.183254,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '31',
    'external_id': '4b75ed5c-e81b-4d75-a4ef-8dffce387fd9',
    'name': 'CE-288 11 de Abril-Avenida 2',
    'short_name': '288',
    'lat': 19.396339843986805,
    'lon': -99.1835709661791,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 15,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '32',
    'external_id': '7b33d340-464d-47ae-a07f-04d0785ad37b',
    'name': 'CE-372 Dr. Roberto Gayol-Tlacoquemécatl',
    'short_name': '372',
    'lat': 19.377966,
    'lon': -99.170272,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '33',
    'external_id': 'b89266bb-5035-46c6-bec9-b2287ee9b396',
    'name': 'CE-434 Jose María Olloqui-Amores',
    'short_name': '434',
    'lat': 19.363698614576656,
    'lon': -99.17118497195588,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '34',
    'external_id': 'df9f2e23-6015-45e3-be47-9681ee56bcb6',
    'name': 'CE-439 Amores-Avenida Coyoacán',
    'short_name': '439',
    'lat': 19.362037,
    'lon': -99.172683,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '35',
    'external_id': 'ea8f9f3d-f51f-4e35-a8b1-689629a448a8',
    'name': 'CE-378 Miguel Laurent-Amores',
    'short_name': '378',
    'lat': 19.375865,
    'lon': -99.168219,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '36',
    'external_id': 'ac8032f2-5d88-428b-8a26-32448c290d5b',
    'name': 'CE-437 Moras-Comunal',
    'short_name': '437',
    'lat': 19.364916,
    'lon': -99.175985,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '37',
    'external_id': 'eac91559-8b08-4a23-8a13-b3a5cbc3397f',
    'name': 'CE-374 Pitágoras-Pilares',
    'short_name': '374',
    'lat': 19.376959,
    'lon': -99.161099,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '38',
    'external_id': 'fbf45c04-d7b3-42e6-921a-6ba289aaee72',
    'name': 'CE-384 Empresa-Poussin',
    'short_name': '384',
    'lat': 19.375865,
    'lon': -99.185573,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '39',
    'external_id': '7bb63b63-4288-4f6d-99e0-34c7f805f315',
    'name': 'CE-348 Indiana-Avenida San Antonio',
    'short_name': '348',
    'lat': 19.3854574,
    'lon': -99.1782718,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '40',
    'external_id': '4771fd01-a609-4494-b5a0-9b9a13e62393',
    'name': 'CE-397 San Lorenzo-Gabriel Mancera',
    'short_name': '397',
    'lat': 19.37313576931919,
    'lon': -99.16706666355822,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '41',
    'external_id': 'ad09be68-706a-477f-8860-fa91a86420d1',
    'name': 'CE-353 Carolina-Holbein',
    'short_name': '353',
    'lat': 19.3823345657493,
    'lon': -99.17888358246273,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '42',
    'external_id': '6546cc34-2240-4073-8d41-0db07cfdecde',
    'name': 'CE-387 Cadiz-Empresa',
    'short_name': '387',
    'lat': 19.374267,
    'lon': -99.180546,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '43',
    'external_id': '807e7b74-3786-4f1d-8aad-73e222ec9aee',
    'name': 'CE-367 Boston -Augusto Rodin',
    'short_name': '367',
    'lat': 19.379593,
    'lon': -99.181351,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '44',
    'external_id': 'b45f855c-06ab-4564-b52b-90b8d1fcea9e',
    'name': 'CE-390-391 Oso-Félix Cuevas',
    'short_name': '390-391',
    'lat': 19.373161,
    'lon': -99.178243,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 47,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '45',
    'external_id': '4b57092e-7db3-4caa-be58-5fdfc56774e5',
    'name': 'CE-303 Montecito-Av. Insurgentes',
    'short_name': '303',
    'lat': 19.394861698080163,
    'lon': -99.17300574486944,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 26,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '46',
    'external_id': '0e0b8cec-c253-4edc-b46b-86030e5ce26d',
    'name': 'CE-370 Tlacoquemécatl-Av. Insurgentes',
    'short_name': '370',
    'lat': 19.378799,
    'lon': -99.176821,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 31,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '47',
    'external_id': 'f60886eb-abc3-419f-93ad-a3486fb1d1df',
    'name': 'CE-354 Boston-Av. Insurgentes',
    'short_name': '354',
    'lat': 19.381714,
    'lon': -99.176664,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '48',
    'external_id': '8b8595c4-4b99-47c9-b9cb-18798af3aba7',
    'name': 'CE-333 Georgia-Carolina',
    'short_name': '333',
    'lat': 19.387624,
    'lon': -99.180978,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '49',
    'external_id': '6cf083a7-b9af-4498-8775-15139e0ab145',
    'name': 'CE-445-446 Riff-Avenida Río Churubusco',
    'short_name': '445-446',
    'lat': 19.35857050753971,
    'lon': -99.15610156956063,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 59,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '50',
    'external_id': 'b397f192-fe32-41ee-8a51-3ecea31ae29f',
    'name': 'CE-429 Pirineos-Av. Popocatépetl (Eje 8)',
    'short_name': '429',
    'lat': 19.363060918104924,
    'lon': -99.15833439679318,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 19,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '51',
    'external_id': '1aba47b5-d46a-458c-94cf-684cf9e264fc',
    'name': 'CE-414 Parroquia-José Ignacio Bartolache',
    'short_name': '414',
    'lat': 19.370213835587535,
    'lon': -99.17385498530166,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 27,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '52',
    'external_id': 'de6d1b56-740c-49b8-8108-9fdc96b3e5be',
    'name': 'CE-432 Carrillo Puerto-Avenida México-Coyoacan',
    'short_name': '432',
    'lat': 19.361245,
    'lon': -99.16239,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 35,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '53',
    'external_id': '5fbb3ae5-290e-43e4-af63-ed7c998ddeb0',
    'name': 'CE-358 Nicolás San Juan-Matias Romero',
    'short_name': '358',
    'lat': 19.380087,
    'lon': -99.16427,
    'rental_methods': ['KEY', 'CREDITCARD'],
    'capacity': 23,
    'electric_bike_surcharge_waiver': False,
    'is_charging': False,
    'eightd_has_key_dispenser': False,
    'has_kiosk': True},
   {'station_id': '55',

In [6]:
# Data frame and inspect
stations_raw = pd.DataFrame(station_json["data"]["stations"])

print("Shape:", stations_raw.shape)
stations_raw.head()
print(stations_raw.columns.tolist())

Shape: (677, 12)
['station_id', 'external_id', 'name', 'short_name', 'lat', 'lon', 'rental_methods', 'capacity', 'electric_bike_surcharge_waiver', 'is_charging', 'eightd_has_key_dispenser', 'has_kiosk']

In [7]:
stations_raw

,station_id,external_id,name,short_name,lat,lon,rental_methods,capacity,electric_bike_surcharge_waiver,is_charging,eightd_has_key_dispenser,has_kiosk
0,1,e961269c-34c4-4b70-8e30-a51aa95a8429,CE-710 Molino del Rey - Glorieta de la Lealtad,710,19.416795,-99.192508,"[KEY, CREDITCARD]",39,False,False,False,True
1,5,3ea89109-d2f3-46eb-9c41-c43742050340,CE-407 Prolongación Xochicalco-General Emilia...,407,19.367266,-99.158656,"[KEY, CREDITCARD]",19,False,False,False,True
2,6,ba78b703-4e5a-44bd-ab2c-1eedc71e11c3,CE-428 Prolongación Uxmal-Av. Popocatépetl (E...,428,19.363404,-99.160395,"[KEY, CREDITCARD]",27,False,False,False,True
3,7,6563d263-2342-46e3-8983-461e68d2d615,CE-427 Avenida México-Coyoacán-Av. Popocatépet...,427,19.364906,-99.162987,"[KEY, CREDITCARD]",19,False,False,False,True
4,8,ec55e597-c8fc-4e86-bcfe-b0e81a494790,CE-443 Bruno Traven-Golondrinas,443,19.359583,-99.162085,"[KEY, CREDITCARD]",31,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
672,697,ea8b036f-bfde-4aa4-8bc0-57405c27fd8a,CE-511 Palestina - Egipto,511,19.463941,-99.182280,"[KEY, CREDITCARD]",27,False,False,False,True
673,698,1f652ea2-4be5-4d30-b73c-2cb7d1266a70,CE-682 Manuel M. Ponce - Fernando M. Villalpando,682,19.353534,-99.189548,"[KEY, CREDITCARD]",23,False,False,False,True
674,699,a1e9daf9-b993-4abb-8e39-66515ffcfa56,CE-681 Guty Cárdenas - Ricardo Castro,681,19.355844,-99.189141,"[KEY, CREDITCARD]",19,False,False,False,True
675,700,09fac974-dc65-4213-b3e6-c5b7440f37df,CE-711 Molino del Rey - Av. Constituyentes,711,19.414108,-99.191983,"[KEY, CREDITCARD]",39,False,False,False,True
676,702,5a26a79f-acdc-40d9-b5e6-f3ab612603c6,CE-524 Malvón - Juan Sarabia,524,19.468119,-99.167268,"[KEY, CREDITCARD]",23,False,False,False,True

- We have 677 active stations as of March 19, 2025
- Short name is the identifier that could be merged

In [8]:
# Define station characteristics 
station_characteristics = [
    c for c in [
        "station_id",
        "name",
        "short_name",
        "lat",
        "lon",
        "capacity",
        "region_id",
        "address"
    ]
    if c in stations_raw.columns
]

stations_ref = stations_raw[station_characteristics].copy()

# Standardize station_id for potential merges
stations_ref["station_id"] = stations_ref["station_id"].astype(str).str.strip()

# Remove duplicate station_ids if any
stations_ref = stations_ref.drop_duplicates(subset=["station_id"])

print("Clean station reference shape:", stations_ref.shape)
stations_ref.head()

Clean station reference shape: (677, 6)

,station_id,name,short_name,lat,lon,capacity
0,1,CE-710 Molino del Rey - Glorieta de la Lealtad,710,19.416795,-99.192508,39
1,5,CE-407 Prolongación Xochicalco-General Emilia...,407,19.367266,-99.158656,19
2,6,CE-428 Prolongación Uxmal-Av. Popocatépetl (E...,428,19.363404,-99.160395,27
3,7,CE-427 Avenida México-Coyoacán-Av. Popocatépet...,427,19.364906,-99.162987,19
4,8,CE-443 Bruno Traven-Golondrinas,443,19.359583,-99.162085,31

In [9]:
# Quality check
print("Missing lat:", stations_ref["lat"].isna().sum())
print("Missing lon:", stations_ref["lon"].isna().sum())

# Save
csv_path = REF_DIR / "stations_gbfs_current.csv"
parquet_path = REF_DIR / "stations_gbfs_current.parquet"

stations_ref.to_csv(csv_path, index=False)
stations_ref.to_parquet(parquet_path, index=False)

print("Saved:")
print(csv_path.resolve())
print(parquet_path.resolve())

Missing lat: 0
Missing lon: 0
Saved:
/Users/francobastida/Desktop/ecobici/data/reference/stations_gbfs_current.csv
/Users/francobastida/Desktop/ecobici/data/reference/stations_gbfs_current.parquet

In [10]:
#Check parquet
stations_ref = pd.read_parquet(REF_DIR / "stations_gbfs_current.parquet")
stations_ref

,station_id,name,short_name,lat,lon,capacity
0,1,CE-710 Molino del Rey - Glorieta de la Lealtad,710,19.416795,-99.192508,39
1,5,CE-407 Prolongación Xochicalco-General Emilia...,407,19.367266,-99.158656,19
2,6,CE-428 Prolongación Uxmal-Av. Popocatépetl (E...,428,19.363404,-99.160395,27
3,7,CE-427 Avenida México-Coyoacán-Av. Popocatépet...,427,19.364906,-99.162987,19
4,8,CE-443 Bruno Traven-Golondrinas,443,19.359583,-99.162085,31
...,...,...,...,...,...,...
672,697,CE-511 Palestina - Egipto,511,19.463941,-99.182280,27
673,698,CE-682 Manuel M. Ponce - Fernando M. Villalpando,682,19.353534,-99.189548,23
674,699,CE-681 Guty Cárdenas - Ricardo Castro,681,19.355844,-99.189141,19
675,700,CE-711 Molino del Rey - Av. Constituyentes,711,19.414108,-99.191983,39
676,702,CE-524 Malvón - Juan Sarabia,524,19.468119,-99.167268,23

In [11]:
def get_active_stations(year: int) -> pd.DataFrame:
    df = pd.read_parquet(YEARLY_DIR / f"ecobici_trips_{year}.parquet")

    start_ids = df["start_station_id"].dropna().astype("Int64").astype(str)
    end_ids = df["end_station_id"].dropna().astype("Int64").astype(str)

    active_ids = pd.concat([start_ids, end_ids], ignore_index=True).drop_duplicates()

    return pd.DataFrame({"station_id": active_ids})

In [12]:
def get_station_map_df(year: int) -> pd.DataFrame:
    stations_year = get_active_stations(year)
    stations_year["station_id"] = stations_year["station_id"].astype(str).str.strip()

    merged = stations_year.merge(
        stations_ref,
        on="station_id",
        how="left"
    )

    print(f"\nYear {year}")
    print("Active stations:", len(merged))
    print("Total stations:", len(merged))
    print("Missing lat:", merged["lat"].isna().sum())
    print("Missing lng:", merged["lon"].isna().sum())

    return merged

In [18]:
import folium

def plot_stations_map(df: pd.DataFrame, title: str):
    # center on Mexico City
    m = folium.Map(
        location=[19.43, -99.13],
        zoom_start=12,
        tiles="CartoDB positron"
    )
    for _, row in df.dropna(subset=["lat", "lon"]).iterrows():
        folium.CircleMarker(
            location=[row["lat"], row["lon"]],
            radius=2,
            color="blue",
            fill=True,
            fill_opacity=0.6,
            popup=str(row.get("station_id", ""))
        ).add_to(m)

    return m

In [14]:
df_2018 = get_station_map_df(2018)
df_2025 = get_station_map_df(2025)

Year 2018
Active stations: 482
Total stations: 482
Missing lat: 13
Missing lng: 13

Year 2025
Active stations: 666
Total stations: 666
Missing lat: 34
Missing lng: 34

In [20]:
map_2018 = plot_stations_map(df_2018, "Stations active in 2018")
map_2018
map_2018.save("../outputs/map_2018.html")

In [22]:
map_2025 = plot_stations_map(df_2025, "Stations active in 2025")
map_2025
map_2025.save("../outputs/map_2025.html")